### ISSUE TITLE
omc is not able to work with `oc adm inspect` results

### ISSUE THREAD

**Issue by palonsoro** [gmeghnag/omc#1]
One of the features added to omg during its most recent versions was the ability to work with the results of `oc adm inspect`. 

Most must-gathers resources (those on folders like `cluster-scoped-resources` and `namespaces`) are gathered by `oc adm inspect` commands run inside must-gather container, so if you run `oc adm inspect` yourself, you get an almost equal structure.

In fact, that's the recommended approach [when a must-gather fails](https://access.redhat.com/articles/4971311). So being able to analyze `oc adm inspect` results would be quite important.

**Comment by palonsoro** [comment]
I first had failures with inspects and hence opened this issue, but I later tried with must-gathers and had issues with them as well. Hence I opened #2 for them. Maybe once that is fixed, inspects work as well.

**Comment by gmeghnag** [comment]
fixed with commit 370b1f44dba1b4a6333f01b8a7082ee9bc072e04, release updated
