### ISSUE TITLE
Give "omc use" command the possibility of open more than one must-gather directory

### ISSUE THREAD

**Issue by brunogomes011** [gmeghnag/omc#102]
The omc use command could have any feature for controlling more than 1 must-gather directory simultaneosly. With this, we could avoid applying the omc use command several times in case of comparison of must-gathers.

Example: 

omc use must-gather1-dir 
omc use must-gather2-dir 

omc-mg1 get nodes
omc-mg2 get nodes

We can find a better syntax.

**Comment by brunogomes011** [comment]
Hey @gmeghnag 
Thanks for the message. Yes, it is the same. 
I have tried to find something similar before opening the issue, but I did not find the mentioned one.

**Comment by gmeghnag** [comment]
No problem, I will close this one in favor of the one mentioned.
