### ISSUE TITLE
Add the option to view the prometheus targets. 

### ISSUE THREAD

**Issue by cpassare** [gmeghnag/omc#118]
Must-gather collects these two files:
- monitoring/prometheus/prometheus-k8s-0/active-targets.json
- monitoring/prometheus/prometheus-k8s-1/active-targets.json

They can be used to provide a quick view of the status of the targets, for example using the following jq filter is it possible to have a readable view:

~~~
$ cat prometheus/prometheus-k8s-1/active-targets.json |jq -r '["Target_Name", "Scrape_URL", "Health", "Last_Error"], (.data.activeTargets[] |[.discoveredLabels.__meta_kubernetes_endpoint_address_target_name, .scrapeUrl, .health, .lastError]) |@csv' |column -t -s,
~~~

**Comment by gmeghnag** [comment]
required API: https://github.com/prometheus/prometheus/blob/75fc8a1535c5fd1acca6036b349e76a42a1f6ddf/web/api/v1/api.go#L880-L897
