### ISSUE TITLE
Improve the `customresourcedefinitions` management

### ISSUE THREAD

**Issue by oarribas** [gmeghnag/omc#121]
With #56 , it's possible to work with resources which CRDs are not in the must-gather. As the CRDs for the same resources could be different between different OCP minor versions, and as operators with custom CRDs can be installed, some improvements that could be added:

### Support for different OCP versions

1. Add subdirectories per OCP version in `~/.omc/customresourcedefinitions/`: `4.12`, `4.13`, ...
2. Provide a command to download the CRDs for all the versions from this repo. For example: `omc pull CRD` should download the CRDs for all the versions (from standard OCP installation) from this repo.
2.1 The `omc pull CRD` command should override the local content with the content of the repo if executed again.
3. Use the version as per the must-gahter's `clusterversion` resource.

### Include additional CRDs

1. Add additional subdirectory for "shared" CRDs in `~/.omc/customresourcedefinitions/`, like for example `shared`.

### Order to use the CRDs
Similar to the order explained in #56, if not found in 1, try 2, and if not found, try 3:

1. The CRDs in the must-gather directory (`<must_gather_root>/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/`).
2. The CRDs for the version in the must-gather's `clusterversion` resource from `~/.omc/customresourcedefinitions/<version>`.
3. The CRDs in `~/.omc/customresourcedefinitions/shared`.

### Upgrading to `omc` version with this feature change
As the `~/.omc/customresourcedefinitions/` directory could be already used, when upgrading to a version that includes the new features:
1. Move the CRDs from `~/.omc/customresourcedefinitions/` to `~/.omc/customresourcedefinitions/backups`.
2. If there is the `~/.omc/customresourcedefinitions/backups` directory when executing `omc` commands, show a warning for users to move the content to `~/.omc/customresourcedefinitions/shared` or to remove if no longer needed.

**Comment by gmeghnag** [comment]
Hi @oarribas :)

- _"As the CRDs for the same resources could be different between different OCP minor versions.."_
  The CRD will differ only if between the two OCP versions a newer `apiVersion` for the resource has been released, but even in that case the CRD should contain the older one too; a practical example:
  ```
  $ oc get crd tasks.tekton.dev -o json | jq '.spec.versions[].name'
  v1beta1
  v1
  ```
  As we can see the `tasks.tekton.dev` CRD contains both the newer one and the old one, so, in my opinion, there is no need to burden the `~/.omc/customresourcedefinitions/` folder by adding a CRD for each version of OCP.

  Also, as you mentioned, the cluster CRDs should also be available from the must-gather, and `omc` will always look at it first.

- _"Provide a command to download the CRDs for all the versions from this repo."_
  Good idea to collect some CRDs here in this repo and implement a command to download them, but may be better to open a new issue for that scope only (as I will probably close the current one, with your permission).

**Comment by oarribas** [comment]
Thanks @gmeghnag for the clarification. I'm closing this one as I created #122.
