### ISSUE TITLE
"omc get mc -o custom-columns=NAME:.metadata.name" shows all columns

### ISSUE THREAD

**Issue by rgouveia-redhat** [gmeghnag/omc#135]
$ omc get mc -o custom-columns=NAME:.metadata.name --no-headers
00-master                                                   7649b9274cde2fb50a61a579e3891c8ead2d79c5   3.4.0   86d
00-worker                                                   7649b9274cde2fb50a61a579e3891c8ead2d79c5   3.4.0   86d
01-master-container-runtime                                 7649b9274cde2fb50a61a579e3891c8ead2d79c5   3.4.0   86d
01-master-kubelet                                           7649b9274cde2fb50a61a579e3891c8ead2d79c5   3.4.0   86d
01-worker-container-runtime                                 7649b9274cde2fb50a61a579e3891c8ead2d79c5   3.4.0   86d
01-worker-kubelet                                           7649b9274cde2fb50a61a579e3891c8ead2d79c5   3.4.0   86d
...

Expected:

$ oc get mc -o custom-columns=NAME:.metadata.name --no-headers
00-master
00-worker
01-master-container-runtime
01-master-kubelet
01-worker-container-runtime
01-worker-kubelet
...

**Comment by gmeghnag** [comment]
That's because `custom-columns` output format has not yet been implemented, issue #94 has been opened to support this output, I'll try to spend some time on it during the next month.
