### ISSUE TITLE
[RFE] omc get volumeattachment

### ISSUE THREAD

**Issue by bernzie36** [gmeghnag/omc#142]
Hi,

Can we add the ability to run volumeattachment commands? The following 2 commands in particular:

~~~
omc get volumeattachment
omc get volumeattachment <VA-Name> -oyaml
~~~

Judging by my reference must-gather, it appears the relevant directory for this is `/cluster-scoped-resources/storage.k8s.io/volumeattachments`.

Thanks

**Comment by cchen666** [comment]
I believe get volumeattachment has already been implemented. Are you using an old version?

$ omc get volumeattachment | wc -l
17

**Comment by gmeghnag** [comment]
Yes, `volumeattachment` is already implemented, closing it.
