### ISSUE TITLE
Allow user to set their desired default project from the `~/.omc/omc.json`

### ISSUE THREAD

**Issue by vlours** [gmeghnag/omc#149]
Based on users' SBR, some people are more likely to work mostly with the same project.
- openshift-storage for ODF
- openshift-logging for sbr-monitoring
- [...]

The `~/.omc/omc.json` currently contains only the `contexts` of the different MGs attached to.
It should be easy to get a `default_project` key/value pair to use this one as default instead of the `openshift-logging` hard-coded in the [use.go](https://github.com/gmeghnag/omc/blob/main/cmd/use/use.go#L80-L81C1) file.

Happy to help or discuss about this!

**Comment by gmeghnag** [comment]
TODO: Allow setting default namespace via `omc config --default-namespace=<NAMESPACE>`
