### ISSUE TITLE
MachineConfigPool does not allow to display a single resource when using the full object name

### ISSUE THREAD

**Issue by vlours** [gmeghnag/omc#154]
When running the command `oc get machineconfigpool.machineconfiguration.openshift.io/master`, the output should only contain a single line, where the output is currently displaying the list of MCP.

It's even worse when asking for the Json output as it does not found any resource.
```
$ oc get machineconfigpool.machineconfiguration.openshift.io master -o json
No resources machineconfigpool.machineconfiguration.openshift.io found in default namespace.
```

It's working fine with the shortname, but not the long one. 🙂
```
$ oc get machineconfigpool master [-o json]
```

Impacted version:
```
$ omc version
omc version: v3.6.0-1.el9
hash: a996a79
https://github.com/gmeghnag/omc
```

**Comment by vlours** [comment]
Not really familiar with the `omc` code, but does it related to the missing CDRs from https://github.com/openshift/api/tree/master/machineconfiguration/v1/zz_generated.crd-manifests

**Comment by clarku** [comment]
Hi everyone I'm going to try working on this issue.
