### ISSUE TITLE
Add CRs present in the Hosted Control Planes

### ISSUE THREAD

**Issue by brunogomes011** [gmeghnag/omc#190]
Hello, 

I could observe that the omc does not appear to be able to recognize some resources from HCP. Here are two examples:

HostedCluster 
NodePools

Some resources related to Multi Cluster Engine

ManagedCluster 

We can find all available resources as the list could not be complete.

**Comment by oarribas** [comment]
@brunogomes011 , this is related to #122 .

In a must-gather, all the CRDs are collected and then `omc` can work with all the resources. But by default, an inspect doesn't collect the CRDs (like must-gather does).

If you copy the CRDs from the cluster (or from a must-gather that includes those) in the `cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/` directory of an inspect, or in `~/.omc/customresourcedefinitions/`, `omc` will be able to use those CRDs to recognize those resources.

**Comment by brunogomes011** [comment]
Hello @oarribas 
Thank you for the explanation. I am closing this request then.
