### ISSUE TITLE
Using "omc use" creates and empty ~/.omc.json and nothing works

### ISSUE THREAD

**Issue by palonsoro** [gmeghnag/omc#2]
If I start with with OMC from scratch and I try `omc use /path/to/must-gather`, it just creates an empty json file on `~/.omc.json`.

After that, it just complains of the following with every command I try and does nothing:
```
$ omc get mg
There are no must-gather resources defined.
```

Not sure if it would reproduce with a non-empty `~/.omc.json`, but with a new one, it does for me.

**Comment by gmeghnag** [comment]
fixed with commit 370b1f44dba1b4a6333f01b8a7082ee9bc072e04, release updated
