### ISSUE TITLE
Some abbreviations not supported

### ISSUE THREAD

**Issue by simonkrenger** [gmeghnag/omc#33]
Thanks for making this tool available.

While testing the `omc` tool I quickly found that it does not support all object types, for example `no` (abbreviation for `nodes`), `ing` (abbreviation for `ingress`) or `crds`:

~~~
$ oc get no
NAME                                            STATUS   ROLES    AGE     VERSION
ip-10-0-153-216.eu-central-1.compute.internal   Ready    worker   5h38m   v1.21
[..]
$ omc get no
Invalid object type: no

$ oc get ing
No resources found in default namespace.
$ omc get ing -A
Invalid object type: ing

$ oc get crds -A
NAME                                                              CREATED AT
alertmanagerconfigs.monitoring.coreos.com                         2022-02-07T08:37:29Z
[..]
$ omc get crds -A
Invalid object type: crds
~~~

Other abbreviations such as `po` (Pods) work as expected. `oc api-resources` shows the abbreviations for the CRDs used by a certain cluster, this may be helpful to complete the list of supported abbreviations.

**Comment by gmeghnag** [comment]
@simonkrenger Are you able to provide me with a valid output for an ingress resource?
```
$ oc get ingress <resource>
$ oc get ingress <resource> -o wide
$ oc get ingress <resource> -o yaml | head -10
```

By the way, I have created [this](https://github.com/gmeghnag/omc/issues/38) issue to track the request to support `ingress` resources and [this](https://github.com/gmeghnag/omc/issues/37) issue to track the request to support `crd` resources, this issue (#33) will only be related to the support of the abbreviation `no` for the `node` resource

**Comment by simonkrenger** [comment]
I updated #38 with the output requested above. Keeping this issue to track the `no` abbreviation issue.
