### ISSUE TITLE
List of supported object types in omc

### ISSUE THREAD

**Issue by kevchu3** [gmeghnag/omc#34]
I'm sure there will be a number of issues opened up as enhancements over time for support for various resource types.  It'd be great if `omc api-resources` can be implemented to reflect the current state of supported resource types in `omc`, since there's a fairly large delta right now between `oc` and `omc`.

**Comment by gmeghnag** [comment]
Starting from `omc v1.4` it will be possible to get all the `omc` supported resources executing the following command:
```
omc api-resources [-o wide]
```

_Where `omc` looks for the supported resources?_
From [here](https://raw.githubusercontent.com/gmeghnag/omc/main/api-resources.yaml); every time `omc api-resources` command is executed an HTTP request is performed and the response body is parsed to get all the supported resources for the current and future releases (doing so a user can check if a resource is supported in a newer release).

### Example
```
omc api-resources -o wide
NAME                        SHORTNAMES   APIVERSION   NAMESPACED   KIND                       SINCE
customresourcedefinitions   crd,crds     v1           false        CustomResourceDefinition   v1.4.0
```

**Comment by gmeghnag** [comment]
Deprecated in favor of #56 .
