### ISSUE TITLE
Show message if the must-gather can be used, or an error in other case

### ISSUE THREAD

**Issue by oarribas** [gmeghnag/omc#52]
When running `omc use` without parameters, it shows the must-gather in use:
```
$ omc use [must-gather_directory]

$ omc use
must-gather: "[must-gather_directory_full_path]
namespace: "default"
```

or if the must-gather is not valid:
```
$ omc use [empty_directory]

$ omc use
Some error occurred, wrong must-gather file composition
```

Add the same messages when running the `omc use [must-gather_directory]`

**Comment by mvalsecc** [comment]
As per our offline conversation, I'll be working on this!
