### ISSUE TITLE
omc becomes unusable if invalid must-gather was previously imported

### ISSUE THREAD

**Issue by linuxstudio** [gmeghnag/omc#59]
omc becomes unusable if invalid must-gather was previously imported.
Here is an example to reproduce the issue. `0170-must-gather-dc46.tar.gz.7z` is a directory, that contains a gzipped file:

```
$ ls 0170-must-gather-dc46.tar.gz.7z
must-gather-dc46.tar.gz

$ omc get mg
There are no must-gather resources defined.

$ omc use 0170-must-gather-dc46.tar.gz.7z

$ omc get mg
Some error occurred, wrong must-gather file composition
```

at that point, omc becomes completely unusable (unless one deletes manually the content of `.omc/omc.json`).
For example, if I try to import a new must-gather:

```
$ omc use 0030-must-gather-tbsdmz.tar.gz.gz/
Some error occurred, wrong must-gather file composition
```

**Comment by nstamatelopoulos** [comment]
Hello

I faced the same issue on supportshell after i accidentally tried to open a tar must-gather. I workaround this with deleting the contents of .omc/omc.json file.
