### ISSUE TITLE
Embed in omc the equivalent of "tkn version"

### ISSUE THREAD

**Issue by acancell-redhat** [gmeghnag/omc#61]
Since `oc adm must-gather` is going to support _openshift-pipeline_, it would be useful to have embedded in `omc` the equivalent of `tkn version`

**Comment by gmeghnag** [comment]
This is out of the scope of the tool, `omc` aims to replace `oc` (and not `tkn`) for offline inspection of the resources.

If you want to check Tekton Pipelines and Tekton Triggers version in use in the cluster you can run `oc get sub -n openshift-operators openshift-pipelines-operator-rh -o jsonpath='{.status.currentCSV}'` and then check [OpenShift Pipelines matrix](https://docs.openshift.com/container-platform/4.11/cicd/pipelines/op-release-notes.html#compatibility-support-matrix_op-release-notes).
