### ISSUE TITLE
omc tool does not support `oc version`

### ISSUE THREAD

**Issue by essie-chiang** [gmeghnag/omc#88]
As we know `oc version` is very common command to collect info of OCP. But `omc version` is the version of omc, that is understandable, but it would be better to add the info of oc version in this command or by someway to show the `oc version`.

**Comment by gmeghnag** [comment]
I will close this issue since `oc` version used to collect must-gather is not collected in the must-gather directory (AFAIK).

You should open an issue to the [must-gather ](https://github.com/openshift/must-gather) repository and ask them to collect this info.
